# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run:
          name: Get sub-modules
          command: git submodule update --init --recursive
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install packages
          command: |
            npm install
      - run:
          name: Compile contracts
          command: npx buidler compile
      - run:
          name: Run tests
          command: npx buidler test
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
